# Dockerfile-hosts

FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && \
    apt-get install -y sudo netcat-openbsd iptables iptables-persistent iproute2 dnsutils \
    iputils-ping traceroute net-tools tcpdump curl wget nginx 

# Keep the container running
CMD tail -f /dev/null
