services:
  router:
    build:
      context: .
      dockerfile: Dockerfile-common
    container_name: router
    command: /bin/bash -c "/home/gnasseri/setup-r.sh && tail -f /dev/null"
    networks:
      r-h1-net:
        ipv4_address: 192.168.1.2
      r-h2-net:
        ipv4_address: 10.10.1.2
      r-nat-net:
        ipv4_address: 172.16.1.2
    volumes:
      - /Users/ginanasseri/gnasseri:/home/gnasseri
      - /Users/ginanasseri/gnasseri/setup-r.sh:/home/gnasseri/setup-r.sh
    cap_add:
      - NET_ADMIN
    restart: always

  piconet:
    build:
      context: .
      dockerfile: Dockerfile-common
    container_name: piconet
    command: /bin/bash -c "/home/gnasseri/setup-piconet.sh && tail -f /dev/null"
    networks:
      r-nat-net:
        ipv4_address: 172.16.1.3
      nat-net:
        ipv4_address: 172.20.1.2   # External facing IP for NAT (this is just an example)
    volumes:
      - /Users/ginanasseri/gnasseri:/home/gnasseri
      - /Users/ginanasseri/gnasseri/setup-piconet.sh:/home/gnasseri/setup-piconet.sh
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    restart: always

  h1:
    build:
      context: .
      dockerfile: Dockerfile-common
    container_name: h1
    command: /bin/bash -c "tail -f /dev/null"
    networks:
      r-h1-net:
        ipv4_address: 192.168.1.100
    volumes:
      - /Users/ginanasseri/gnasseri:/home/gnasseri
    cap_add:
      - NET_ADMIN
    restart: always

  h2:
    build:
      context: .
      dockerfile: Dockerfile-common
    container_name: h2
    command: /bin/bash -c "tail -f /dev/null"
    networks:
      r-h2-net:
        ipv4_address: 10.10.1.200
    volumes:
      - /Users/ginanasseri/gnasseri:/home/gnasseri
    cap_add:
      - NET_ADMIN
    restart: always

networks:
  r-h1-net:
    name: r-h1
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

  r-h2-net:
    name: r-h2
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

  r-nat-net:
    name: r-pico
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

  nat-net:       # Add the external network for NAT
    name: pico-nat
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24  # Example subnet for external network

