# Dockerfile-router

FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y \
    sudo netcat-openbsd iptables iptables-persistent iproute2 iputils-ping \
    dnsutils traceroute net-tools tcpdump curl wget nginx 

# Run setup script and keep the container running
CMD ["/bin/bash", "-c", "/home/dockerNet/setup-router.sh && tail -f /dev/null"]
